### ISSUE TITLE
extension or wep

### ISSUE THREAD

**Issue by apolloS125** [L4743exec/RNN-ML#1]
# เอาไรดี

1. wep

- ใส่ข้อความในช่องแล้วกดปุ่ม

![ภาพ](https://github.com/user-attachments/assets/6b0c4e49-a9d7-4fab-83d0-24eaf1af42dc)

2.extension

-เอาเม้าคลุมข้อความแล้วคลิกขาวเพื่อวิเคราะห์ประโยคนั้น

![ภาพ](https://github.com/user-attachments/assets/7def8954-0802-4571-ae5b-cbd45eb3747c)

**Comment by lataeq** [comment]
web +1

**Comment by apolloS125** [comment]
เออวะทำไมกุไม่ถามในกลุ่มวะ
